apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  labels:
    app: apm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-server
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      nodeSelector:
        app: elk
      containers:
        - name: apm-server
          image: docker.elastic.co/apm/apm-server:8.17.0
          ports:
            - containerPort: 8200
              name: apm-server
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: KIBANA_HOST
              value: "http://kibana:5601"
---
apiVersion: v1
kind: Service
metadata:
  name: apm-server
  labels:
    app: apm-server
spec:
  ports:
    - port: 8200
      targetPort: 8200
      name: apm-server
  selector:
    app: apm-server
  type: ClusterIP
