apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config-12
data:
  Caddyfile: |
    kibana.chiawen.dev {
      reverse_proxy kibana:5601
      log {
        output file /var/log/kibana {
          roll_size     100MiB
        }
      }
    }

    apm.chiawen.dev {
      reverse_proxy apm-server:8200
      log {
        output file /var/log/apm {
          roll_size     100MiB
        }
      }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  labels:
    app: caddy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      nodeSelector:
        app: elk
      containers:
      - name: caddy
        image: caddy:2.7-alpine
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: caddy-config
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
        - name: caddy-data
          mountPath: /data
      volumes:
      - name: caddy-config
        configMap:
          name: caddy-config-12
      - name: caddy-data
        persistentVolumeClaim:
          claimName: caddy-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: caddy
  labels:
    app: caddy
spec:
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: caddy
  type: LoadBalancer
  loadBalancerIP: 35.185.157.239