apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config-2
  labels:
    app: kibana
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.publicBaseUrl: "https://elk.chiawen.dev"
    elasticsearch.hosts: ["http://elasticsearch:9200"]
    xpack.encryptedSavedObjects:
      encryptionKey: "min-32-byte-long-strong-encryption-key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      nodeSelector:
        app: elk
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.17.0
        ports:
        - containerPort: 5601
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
      volumes:
      - name: config
        configMap:
          name: kibana-config-2
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
    targetPort: 5601
    name: http
  selector:
    app: kibana
  type: ClusterIP
